// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: rpc.proto

package main

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GenSessionCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId    string `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	MyRole    int32  `protobuf:"varint,3,opt,name=myRole,proto3" json:"myRole,omitempty"`
	OtherRole int32  `protobuf:"varint,4,opt,name=otherRole,proto3" json:"otherRole,omitempty"`
}

func (x *GenSessionCmd) Reset() {
	*x = GenSessionCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenSessionCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenSessionCmd) ProtoMessage() {}

func (x *GenSessionCmd) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenSessionCmd.ProtoReflect.Descriptor instead.
func (*GenSessionCmd) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *GenSessionCmd) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *GenSessionCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GenSessionCmd) GetMyRole() int32 {
	if x != nil {
		return x.MyRole
	}
	return 0
}

func (x *GenSessionCmd) GetOtherRole() int32 {
	if x != nil {
		return x.OtherRole
	}
	return 0
}

type RegProxyCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerId string `protobuf:"bytes,1,opt,name=peerId,proto3" json:"peerId,omitempty"`
}

func (x *RegProxyCmd) Reset() {
	*x = RegProxyCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegProxyCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegProxyCmd) ProtoMessage() {}

func (x *RegProxyCmd) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegProxyCmd.ProtoReflect.Descriptor instead.
func (*RegProxyCmd) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RegProxyCmd) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

type ExtendCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Relay     string `protobuf:"bytes,1,opt,name=relay,proto3" json:"relay,omitempty"`
	Joint     string `protobuf:"bytes,2,opt,name=joint,proto3" json:"joint,omitempty"`
	SessionId string `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *ExtendCmd) Reset() {
	*x = ExtendCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtendCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendCmd) ProtoMessage() {}

func (x *ExtendCmd) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendCmd.ProtoReflect.Descriptor instead.
func (*ExtendCmd) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *ExtendCmd) GetRelay() string {
	if x != nil {
		return x.Relay
	}
	return ""
}

func (x *ExtendCmd) GetJoint() string {
	if x != nil {
		return x.Joint
	}
	return ""
}

func (x *ExtendCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RelayMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionID string `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Msg       []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RelayMsg) Reset() {
	*x = RelayMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RelayMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayMsg) ProtoMessage() {}

func (x *RelayMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayMsg.ProtoReflect.Descriptor instead.
func (*RelayMsg) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RelayMsg) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *RelayMsg) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type GenCircuitCmd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Des       string `protobuf:"bytes,1,opt,name=des,proto3" json:"des,omitempty"`
	SessionId string `protobuf:"bytes,2,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *GenCircuitCmd) Reset() {
	*x = GenCircuitCmd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenCircuitCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenCircuitCmd) ProtoMessage() {}

func (x *GenCircuitCmd) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenCircuitCmd.ProtoReflect.Descriptor instead.
func (*GenCircuitCmd) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *GenCircuitCmd) GetDes() string {
	if x != nil {
		return x.Des
	}
	return ""
}

func (x *GenCircuitCmd) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GossipMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DesHash   string `protobuf:"bytes,1,opt,name=desHash,proto3" json:"desHash,omitempty"`
	Join      string `protobuf:"bytes,2,opt,name=join,proto3" json:"join,omitempty"`
	SessionId string `protobuf:"bytes,3,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
}

func (x *GossipMsg) Reset() {
	*x = GossipMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMsg) ProtoMessage() {}

func (x *GossipMsg) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMsg.ProtoReflect.Descriptor instead.
func (*GossipMsg) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *GossipMsg) GetDesHash() string {
	if x != nil {
		return x.DesHash
	}
	return ""
}

func (x *GossipMsg) GetJoin() string {
	if x != nil {
		return x.Join
	}
	return ""
}

func (x *GossipMsg) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok   bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *Res) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Res) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_rpc_proto protoreflect.FileDescriptor

var file_rpc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0x7b, 0x0a, 0x0d, 0x67, 0x65, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43,
	0x6d, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x79, 0x52, 0x6f,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6d, 0x79, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x25,
	0x0a, 0x0b, 0x72, 0x65, 0x67, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6d, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70,
	0x65, 0x65, 0x72, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x43,
	0x6d, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x69, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x3a, 0x0a, 0x08,
	0x72, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x3f, 0x0a, 0x0d, 0x67, 0x65, 0x6e, 0x43,
	0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x43, 0x6d, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x09, 0x67, 0x6f, 0x73,
	0x73, 0x69, 0x70, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x73, 0x48, 0x61, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x73, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x6a, 0x6f, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6a, 0x6f, 0x69, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x29, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xa5, 0x02,
	0x0a, 0x03, 0x52, 0x70, 0x63, 0x12, 0x34, 0x0a, 0x10, 0x47, 0x65, 0x6e, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x74, 0x6f, 0x50, 0x65, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x67, 0x65, 0x6e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x43, 0x6d, 0x64, 0x1a, 0x09,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x72, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0d, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x11, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x72, 0x65, 0x67, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6d, 0x64, 0x1a,
	0x09, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x72, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0d,
	0x45, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x0f, 0x2e,
	0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x64, 0x43, 0x6d, 0x64, 0x1a, 0x09,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x72, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0c, 0x53,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x12, 0x0e, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x72, 0x65, 0x6c, 0x61, 0x79, 0x4d, 0x73, 0x67, 0x1a, 0x09, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x72, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x43,
	0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x12, 0x13, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x67, 0x65,
	0x6e, 0x43, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x43, 0x6d, 0x64, 0x1a, 0x09, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x72, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0b, 0x47, 0x6f, 0x73, 0x73,
	0x69, 0x70, 0x4a, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0f, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x67,
	0x6f, 0x73, 0x73, 0x69, 0x70, 0x4d, 0x73, 0x67, 0x1a, 0x09, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x72, 0x65, 0x73, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData = file_rpc_proto_rawDesc
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proto_rawDescData)
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rpc_proto_goTypes = []interface{}{
	(*GenSessionCmd)(nil), // 0: main.genSessionCmd
	(*RegProxyCmd)(nil),   // 1: main.regProxyCmd
	(*ExtendCmd)(nil),     // 2: main.extendCmd
	(*RelayMsg)(nil),      // 3: main.relayMsg
	(*GenCircuitCmd)(nil), // 4: main.genCircuitCmd
	(*GossipMsg)(nil),     // 5: main.gossipMsg
	(*Res)(nil),           // 6: main.res
}
var file_rpc_proto_depIdxs = []int32{
	0, // 0: main.Rpc.GenSessiontoPeer:input_type -> main.genSessionCmd
	1, // 1: main.Rpc.RegisterProxy:input_type -> main.regProxyCmd
	2, // 2: main.Rpc.ExtendSession:input_type -> main.extendCmd
	3, // 3: main.Rpc.SendRelayMsg:input_type -> main.relayMsg
	4, // 4: main.Rpc.GenCircuit:input_type -> main.genCircuitCmd
	5, // 5: main.Rpc.GossipJoint:input_type -> main.gossipMsg
	6, // 6: main.Rpc.GenSessiontoPeer:output_type -> main.res
	6, // 7: main.Rpc.RegisterProxy:output_type -> main.res
	6, // 8: main.Rpc.ExtendSession:output_type -> main.res
	6, // 9: main.Rpc.SendRelayMsg:output_type -> main.res
	6, // 10: main.Rpc.GenCircuit:output_type -> main.res
	6, // 11: main.Rpc.GossipJoint:output_type -> main.res
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenSessionCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegProxyCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtendCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RelayMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenCircuitCmd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_rawDesc = nil
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
